apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: stress
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  template:
    metadata:
      labels:
        karpenter.nodepool/name: stress
    spec:
      nodeClassRef:
        name: default
        kind: AKSNodeClass
        group: karpenter.azure.com
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - D
  limits:
    cpu: 40
      # memory: 1000Gi
  weight: 50